<xsl:stylesheet
	version="2.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:xlink="http://www.w3.org/1999/xlink"
	>
	
	<xsl:template match="dashboard">
		<xsl:call-template name="display_menu_content">
			<xsl:with-param name="menu_content">
				<h3>Daizy Minimalistic Admin Template</h3>
				<p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Arcu non sodales neque sodales ut etiam sit amet nisl. Ullamcorper sit amet risus nullam eget. Nibh tortor id aliquet lectus proin. Eget nunc scelerisque viverra mauris in aliquam sem. Nisi lacus sed viverra tellus in hac habitasse platea. Pellentesque nec nam aliquam sem et tortor consequat id. Eu consequat ac felis donec et odio pellentesque diam. Urna porttitor rhoncus dolor purus non enim. Nec ultrices dui sapien eget.</p>
				<p>Parturient montes nascetur ridiculus mus. Sem et tortor consequat id porta nibh venenatis cras. Tristique senectus et netus et. In eu mi bibendum neque egestas congue. Curabitur vitae nunc sed velit dignissim sodales. Amet tellus cras adipiscing enim eu turpis egestas pretium. Vitae aliquet nec ullamcorper sit amet risus. Auctor augue mauris augue neque gravida in fermentum et. Amet porttitor eget dolor morbi. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis.</p>
				<p>Vel orci porta non pulvinar. Nec dui nunc mattis enim ut tellus elementum sagittis. Suspendisse interdum consectetur libero id faucibus. In metus vulputate eu scelerisque felis imperdiet. Vitae semper quis lectus nulla at. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Elementum eu facilisis sed odio morbi quis commodo odio. Accumsan in nisl nisi scelerisque eu ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada. At consectetur lorem donec massa sapien faucibus et molestie. Pellentesque habitant morbi tristique senectus. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Ultricies lacus sed turpis tincidunt id aliquet. Tempor commodo ullamcorper a lacus vestibulum.</p>
				<p>Adipiscing bibendum est ultricies integer quis auctor elit sed. Eu augue ut lectus arcu bibendum at varius vel pharetra. Non tellus orci ac auctor augue mauris augue. Amet tellus cras adipiscing enim. Ultricies integer quis auctor elit sed vulputate mi. Non enim praesent elementum facilisis leo vel fringilla est ullamcorper. Vestibulum morbi blandit cursus risus at ultrices mi tempus imperdiet. Pharetra vel turpis nunc eget lorem dolor sed. Sit amet dictum sit amet justo donec enim diam vulputate. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Arcu cursus euismod quis viverra nibh. Sem fringilla ut morbi tincidunt augue interdum velit. At in tellus integer feugiat scelerisque varius morbi. Dignissim sodales ut eu sem. Urna cursus eget nunc scelerisque viverra mauris in. Facilisis mauris sit amet massa vitae tortor condimentum lacinia quis. Vitae congue eu consequat ac. A erat nam at lectus urna duis. Sem viverra aliquet eget sit amet tellus. Faucibus vitae aliquet nec ullamcorper.</p>
				<p>Leo urna molestie at elementum eu facilisis sed odio. Eget mi proin sed libero enim. Condimentum mattis pellentesque id nibh tortor id aliquet lectus proin. Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Dolor sit amet consectetur adipiscing elit. Vitae turpis massa sed elementum. Quis vel eros donec ac odio tempor orci dapibus. Nunc sed velit dignissim sodales ut eu sem integer. Ante in nibh mauris cursus mattis. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla.</p>
			</xsl:with-param>
		</xsl:call-template>
	</xsl:template>
	
</xsl:stylesheet>